apiVersion: apps/v1
kind: Deployment
metadata:
  name: complain
  namespace: airbnb
  labels:
    app: complain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complain
  template:
    metadata:
      labels:
        app: complain
    spec:
      containers:
        - name: complain
          image: 654789606772.dkr.ecr.ap-northeast-2.amazonaws.com/user03-complain:v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1000m"
              memory: "256Mi"
            limits:
              cpu: "2500m"  
              memory: "512Mi"