apiVersion: apps/v1
kind: Deployment
metadata:
  name: complain
  namespace: airbnb
  labels:
    app: complain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complain
  template:
    metadata:
      labels:
        app: complain
    spec:
      containers:
        - name: complain
          image: 654789606772.dkr.ecr.ap-northeast-2.amazonaws.com/user03-complain:v7
          ports:
            - containerPort: 8080          
          args:
          - /bin/sh
          - -C
          - touch /tmp/healthy; sleep 60; rm -rf /tmp/healthy; sleep 600          
          livenessProbe:            
            exec:
              command: 
              - cat
              - /tmp/healthy
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5